# api/serializers.py

from rest_framework import serializers
from datetime import date
from .models import Author, Book

class BookSerializer(serializers.ModelSerializer):
    """
    Serializer for the Book model.
    Handles serialization, deserialization, and validation for Book instances.
    """
    class Meta:
        model = Book
        fields = ['id', 'title', 'publication_year', 'author'] # Include 'id' for updates/retrievals
        read_only_fields = ['id'] # 'id' is typically read-only, generated by the database

    def validate_publication_year(self, value):
        """
        Custom validation to ensure publication_year is not in the future.
        """
        current_year = date.today().year
        if value > current_year:
            raise serializers.ValidationError(
                f"Publication year cannot be in the future. Current year is {current_year}."
            )
        if value < 0: # Optionally prevent negative years
            raise serializers.ValidationError("Publication year cannot be negative.")
        return value

class AuthorSerializer(serializers.ModelSerializer):
    """
    Serializer for the Author model.
    Includes nested serialization to display books associated with each author.
    """
    # Use BookSerializer to display a list of books for each author.
    # many=True indicates that an author can have multiple books.
    # read_only=True means these nested books are displayed but not created/updated via AuthorSerializer.
    # If you wanted to create/update books through the AuthorSerializer, you'd remove read_only=True
    # and handle the nested writes in the AuthorSerializer's create/update methods.
    books = BookSerializer(many=True, read_only=True)

    class Meta:
        model = Author
        fields = ['id', 'name', 'books'] # Include 'books' to show nested serialized books
        read_only_fields = ['id'] # 'id' is typically read-only