# Generated by Django 5.2.5 on 2025-09-17 23:21

import datetime
import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bookshelf', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Optional: A short biography of the author.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, help_text='Optional: The genre or category of the book (e.g., Fiction, Sci-Fi, Fantasy).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text='The full name of the author.', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(help_text='The author of the book.', on_delete=django.db.models.deletion.CASCADE, to='bookshelf.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=None, help_text='The International Standard Book Number (13 digits), must be unique.', max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(default=datetime.date(1900, 1, 1), help_text='The date the book was first published.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='The title of the book.', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Optional: User's date of birth.", null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', related_query_name='customuser', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text="Optional: User's profile photo.", null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission'),
        ),
    ]
