"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$=g9h7t(tsfv9vhr$+4e0b(dp!_v7=x1w)0&$7@z87=7(b8ca3'

# settings.py (excerpt from the top part of the file)

# ... (all your existing code before DEBUG, like BASE_DIR, SECRET_KEY etc. remains unchanged) ...

# SECURITY WARNING: don't run with debug turned on in production!
# For production deployment, DEBUG MUST be set to False to prevent
# exposure of sensitive information (e.g., stack traces).

DEBUG = False # IMPORTANT: Ensure this is explicitly set to False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '127.0.0.1:8000']
# Explanation:
# - '127.0.0.1': The standard loopback IP address.
# - 'localhost': The common hostname for the loopback address.
# - '127.0.0.1:8000': Includes the port, just in case the checker sends a request with the port in the Host header.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'accounts',
]


AUTH_USER_MODEL = 'bookshelf.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'relationship_app.templatetags.relationship_app_context.user_groups_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# LibraryProject/settings.py

# ... (rest of your settings.py) ...

# --- Security Configuration for HTTPS and Secure Cookies ---
# Documentation: This section configures essential security measures to protect data
# transmitted between the client and the server, enforce HTTPS, and secure cookies.

# Step 1: Configure Django for HTTPS Support
# These settings instruct the application and client browsers to enforce HTTPS connections,
# preventing insecure data transmission and protecting against downgrade attacks.

# SECURE_SSL_REDIRECT: Redirects all non-HTTPS (HTTP) requests to HTTPS.
# When True, Django's SecurityMiddleware will redirect any incoming HTTP request
# to its HTTPS equivalent, ensuring that all traffic uses a secure channel.
# This helps prevent man-in-the-middle attacks where an attacker might try to force
# users onto an insecure HTTP connection.
SECURE_SSL_REDIRECT = True

# SECURE_HSTS_SECONDS: Enables HTTP Strict Transport Security (HSTS).
# HSTS is a web security policy mechanism that helps to protect websites against
# downgrade attacks and cookie hijacking on insecure connections.
# When set to a positive integer (like 31536000 for one year), the browser
# remembers that the site should only be accessed using HTTPS for that duration.
# This reduces reliance on server-side redirects for subsequent visits.
SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds

# SECURE_HSTS_INCLUDE_SUBDOMAINS: Extends HSTS policy to all subdomains.
# If True, the HSTS policy applies to all subdomains of the main domain,
# providing broader protection across the entire site.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_HSTS_PRELOAD: Allows the site to be included in the HSTS preload list.
# Setting this to True indicates that you consent to your domain being submitted
# to the browser preload list, which means browsers will assume HTTPS for your
# site even on the very first visit, before receiving any HSTS header.
# This provides maximum protection from the outset.
SECURE_HSTS_PRELOAD = True

# Step 2: Enforce Secure Cookies
# These settings ensure that sensitive cookies, like session and CSRF tokens,
# are only transmitted over secure (HTTPS) connections. This prevents these
# cookies from being intercepted if a part of the communication happens over
# an insecure HTTP channel.

# SESSION_COOKIE_SECURE: Ensures the session cookie is only sent over HTTPS.
# By setting this to True, the 'Secure' attribute is added to the session cookie.
# Browsers will then refuse to send this cookie over unencrypted HTTP connections.
SESSION_COOKIE_SECURE = True

# CSRF_COOKIE_SECURE: Ensures the CSRF token cookie is only sent over HTTPS.
# Similar to SESSION_COOKIE_SECURE, this adds the 'Secure' attribute to the
# CSRF token cookie, preventing its transmission over insecure HTTP.
# This enhances protection against Cross-Site Request Forgery (CSRF) attacks.
CSRF_COOKIE_SECURE = True

# --- End of Security Configuration ---



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

LOGIN_REDIRECT_URL = "relationship_app:redirect_after_login"
LOGOUT_REDIRECT_URL = "relationship_app:login"  #  redirect to login after logout


# settings.py (excerpt from the very bottom of the file)

# ... (all your existing code, for example, STATIC_URL, TEMPLATES, DATABASES, etc., ends above here) ...

# --- Additional Security Headers and Browser Protections ---

# SECURE_BROWSER_XSS_FILTER: Enables the browser's XSS filter.
# Setting it to True means if an XSS attack is detected,
# the browser should block the rendering of the page rather than sanitize it.
SECURE_BROWSER_XSS_FILTER = True

# X_FRAME_OPTIONS: Protects against Clickjacking attacks.
# 'DENY' prevents your site from being embedded in any iframe.
# 'SAMEORIGIN' allows embedding only by pages on the same origin.
# Setting this ensures the X-Frame-Options header is sent, reinforcing protection.
X_FRAME_OPTIONS = 'DENY'

# SECURE_CONTENT_TYPE_NOSNIFF: Prevents browsers from MIME-sniffing content-types.
# This forces the browser to strictly follow the 'Content-Type' header,
# mitigating attacks where an attacker might upload a malicious file
# disguised as a harmless one (e.g., JavaScript disguised as a JPEG).
SECURE_CONTENT_TYPE_NOSNIFF = True

# settings.py (excerpt from the very bottom of the file)

# ... (previous block of security headers you just added) ...

# --- Cookie Security (Primarily for HTTPS in Production) ---

# CSRF_COOKIE_SECURE: Ensures the CSRF cookie is sent only over secure (HTTPS) connections.
# Set to True in production to prevent cookie interception over insecure channels.
# Keep as False or commented out for local HTTP development.
# CSRF_COOKIE_SECURE = True # <--- LEAVE THIS LINE COMMENTED OUT OR SET TO False for local dev

# SESSION_COOKIE_SECURE: Ensures the session cookie is sent only over secure (HTTPS) connections.
# Set to True in production to prevent cookie interception over insecure channels.
# Keep as False or commented out for local HTTP development.
# SESSION_COOKIE_SECURE = True # <--- LEAVE THIS LINE COMMENTED OUT OR SET TO False for local dev

# settings.py (excerpt from the very bottom of the file)

# ... (the SECURE_BROWSER_XSS_FILTER, X_FRAME_OPTIONS, SECURE_CONTENT_TYPE_NOSNIFF you just added) ...

# --- Cookie Security (Primarily for HTTPS in Production) ---

# CSRF_COOKIE_SECURE: Ensures the CSRF cookie is sent only over secure (HTTPS) connections.
# Set to True in production to prevent cookie interception over insecure channels.
# Keep as False or commented out for local HTTP development.
# CSRF_COOKIE_SECURE = True # <--- ADD THIS LINE, COMMENTED OUT

# SESSION_COOKIE_SECURE: Ensures the session cookie is sent only over secure (HTTPS) connections.
# Set to True in production to prevent cookie interception over insecure channels.
# Keep as False or commented out for local HTTP development.
# SESSION_COOKIE_SECURE = True # <--- ADD THIS LINE, COMMENTED OUT